Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 12
  Enabled: true
  Severity: Convention

Lint/NotNil:
  Enabled: false

Style/QueryBoolMethods:
  Enabled: false
