name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"
jobs:
  style:
      runs-on: ubuntu-latest
      container:
        image: crystallang/crystal
      steps:
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: Format
          run: crystal tool format --check
        - name: Lint
          uses: crystal-ameba/github-action@v0.2.12
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest]
          crystal:
            - latest
            - nightly
            - 1.0.0
            - 0.36.1
      runs-on: ${{ matrix.os }}
      container: crystallang/crystal:${{ matrix.crystal }}-alpine

      # Service containers to run with `container-job`
      services:
        # Label used to access the service container
        redis:
          # Docker Hub image
          image: redis
          # Set health checks to wait until redis has started
          options: >-
            --health-cmd "redis-cli ping"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      steps:
        - name: Install LibSSH2
          run: apk add --no-cache libssh2 libssh2-dev libssh2-static iputils
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: Install dependencies
          run: shards install --ignore-crystal-version
        - name: Run tests
          run: crystal spec -v --error-trace
          env:
            REDIS_URL: redis://redis:6379
