name: CI
on: push
jobs:
  style:
      runs-on: ubuntu-latest
      container:
        image: crystallang/crystal
      steps:

        - name: Check out repository code
          uses: actions/checkout@v2
        - name: Format
          run: crystal tool format --check
        - name: Lint
          uses: crystal-ameba/github-action@v0.2.12
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest]
          crystal: [crystallang/crystal:latest-alpine, crystallang/crystal:nightly-alpine]
      runs-on: ${{ matrix.os }}
      container:
        image: ${{ matrix.crystal }}
      steps:
        - name: Install LibSSH2
          run: apk add --no-cache libssh2 libssh2-dev libssh2-static iputils
        - name: Install Redis
          run: docker run -d -p 6379:6379 redis:6-alpine
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: Install dependencies
          run: shards install --ignore-crystal-version
        - name: Run tests
          run: crystal spec -v --error-trace
